function theta = torque_balance(Points,theta)
err = inf;
while err > 1e-5
    Pose = [Points,theta];
    pathSegObj =                                  ...
        connect(robotics.DubinsConnection,        ...
                Pose(1:end-1,:),Pose(2:end,:));
    copy = theta;
    theta = theta +                               ...
            torque_adjust(theta,pathSegObj)/60;
    err = norm(copy-theta);
end

function theta = torque_adjust(theta,pathSegObj)
% 顺扭矩微调角度
torque_adjust_core = @(theta,r,I,si,O,so)         ...
    (abs(I)-79)*(1-cos(si/r)) +                   ...
    (79-abs(O))*(1-cos(so/r));
num = length(theta);
theta(1) = torque_adjust_core(theta(1),1,         ...
    'L',0,pathSegObj{1}.MotionTypes{1},           ...
    pathSegObj{1}.MotionLengths(1));
for idx = 2:num-1
    theta(idx) = torque_adjust_core(theta(idx),1, ...
        pathSegObj{idx-1}.MotionTypes{3},         ...
        pathSegObj{idx-1}.MotionLengths(3),       ...
        pathSegObj{idx}.MotionTypes{1},           ...
        pathSegObj{idx}.MotionLengths(1));
end
theta(num) = torque_adjust_core(theta(num),1,     ...
    pathSegObj{num-1}.MotionTypes{3},             ...
    pathSegObj{num-1}.MotionLengths(3),'L',0);